# Generated by Django 3.2.5 on 2021-10-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sock',
            new_name='stock',
        ),
    ]
